BASE_DIR="/opt/nginxbandits"
PRIMARY_DOMAIN=""
NS_DOMAIN=""

MAX_LOGINS_DEFAULT=2

PORT_SSH=22
PORT_DROPBEAR=109
PORT_DROPBEAR_ALT=143
PORT_WS_HTTP=80
PORT_WS_HTTPS=443
PORT_SOCKS=1080
PORT_UDP_CUSTOM=36712
PORT_UDPGW=7300
PORT_DNSTT=5300
PORT_SSL_ALT1=447
PORT_SSL_ALT2=777

DB_PATH="/opt/nginxbandits/core/database.db"
LOG_DIR="/opt/nginxbandits/logs"

FOOTER_MSG=""
